
CREATE TABLE USER (   
    USERID int AUTO_INCREMENT,
    USERNAME varchar(30) NOT NULL,
    PASSWORD varchar(255) NOT NULL,   
    ISACTIVE varchar(1),
	CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERID)
);

CREATE TABLE USER_INFO (   
    USERINFOID int AUTO_INCREMENT,
    USERID int,
    EMAILID varchar(60),
    FIRSTNAME  varchar(60) NOT NULL,
    MIDDLENAME  varchar(60),
    LASTNAME varchar(60),
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERINFOID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);

CREATE TABLE USER_ADDRESS (   
    USERADDRESSID int AUTO_INCREMENT,
    USERID int,
    ADDRESS varchar(255),
    CITY varchar(255),
    PINCODE  int,
    COUNTRY varchar(255),
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERADDRESSID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);

CREATE TABLE ROLE (   
    ROLEID int AUTO_INCREMENT,
    ROLENAME varchar(255) NOT NULL,
    ROLEDESCRIPTION varchar(255),
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (ROLEID)
);

CREATE TABLE USER_ROLE (   
    USERROLEID int AUTO_INCREMENT,
    USERID int ,
    ROLEID int ,
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERROLEID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID),
    FOREIGN KEY (ROLEID) REFERENCES ROLE(ROLEID)
);

commit;

#drop table USER_ROLE;
#drop table ROLE;
#drop table USER_ADDRESS;
#drop table USER_INFO;
#drop table USER;

commit;

#alter table user ADD UNIQUE(username); 
#alter table user MODIFY COLUMN PASSWORD varchar(255) NOT NULL; 
commit;
#https://www.tmforum.org/resources/specification/tmf620-product-catalog-management-api-rest-specification-r17-5-0/
#DROP TABLE PRODUCTOFFERING;
CREATE TABLE PRODUCTOFFERING (   
    PRODUCTOFFERINGID int AUTO_INCREMENT,
    NAME varchar(255) NOT NULL, 
    HREF varchar(255),      
    DESCRIPTION varchar(255),
    ISBUNDLE varchar(1),
    LASTUPDATE DATE,
    LIFECYCLESTATUS varchar(30),
    VALIDFOR varchar(10),
    VERSION varchar(10),
    TYPE varchar(10),
    BASETYPE varchar(10),
	SCHEMALOCATION varchar(10),
	ISSELLABLE varchar(1),    
	CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (PRODUCTOFFERINGID)
);
alter table PRODUCTOFFERING ADD UNIQUE(NAME); 
commit;
#DROP TABLE PRODUCTOFFERINGPRICE;
CREATE TABLE PRODUCTOFFERINGPRICE ( 
	PRODUCTOFFERINGPRICEID int AUTO_INCREMENT,
    NAME varchar(255) NOT NULL, 
    DESCRIPTION varchar(255),
    VALIDFOR varchar(10),
	PRICETYPE varchar(10),
    UNITOFMEASURE varchar(10),
	RECURRINGCHARGEPRICE varchar(10),
    VERSION varchar(10),
    PRODUCTOFFERINGID INT,
    HREF varchar(255),
    TYPE varchar(10),
    BASETYPE varchar(10),
    SCHEMALOCATION varchar(10),
	ISBUNDLE varchar(1),
	CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (PRODUCTOFFERINGPRICEID),
    FOREIGN KEY (PRODUCTOFFERINGID) REFERENCES PRODUCTOFFERING (PRODUCTOFFERINGID)
);
#DROP TABLE PRODUCTSPECIFICATIONREF;
CREATE TABLE PRODUCTSPECIFICATIONREF ( 
	PRODUCTSPECIFICATIONREFID int AUTO_INCREMENT,
    PRODUCTOFFERINGID INT,
    NAME varchar(255) NOT NULL, 
    VERSION varchar(10),
    HREF varchar(255),
    REFERREDTYPE varchar(10), 
	CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (PRODUCTSPECIFICATIONREFID),
    FOREIGN KEY (PRODUCTOFFERINGID) REFERENCES PRODUCTOFFERING (PRODUCTOFFERINGID)
);
COMMIT;


