INSERT INTO USER (USERNAME, PASSWORD, ISACTIVE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('admin', 'admin', 'Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;
INSERT INTO USER_INFO (USERID, EMAILID, FIRSTNAME,MIDDLENAME,LASTNAME,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((select userid from USER where username='admin'), 'karthik727@gmail.com', 'karthik',null,'kumbhari','admin',sysdate(),'admin',sysdate(),'admin');
commit;
INSERT INTO USER_ADDRESS (USERID, ADDRESS, CITY,PINCODE,COUNTRY,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((select userid from USER where username='admin'), 'ECO WORLD BT', 'BENGALURU',560066,'INDIA','admin',sysdate(),'admin',sysdate(),'admin');
commit;
INSERT INTO ROLE (ROLENAME, ROLEDESCRIPTION,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( 'admin', 'Full access to the system','admin',sysdate(),'admin',sysdate(),'admin'); 
 INSERT INTO ROLE (ROLENAME, ROLEDESCRIPTION,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( 'user', 'User access to the system','admin',sysdate(),'admin',sysdate(),'admin'); 
 commit;
INSERT INTO USER_ROLE (USERID, ROLEID,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( (select userid from USER where username='admin'), (select ROLEID from ROLE where ROLENAME='admin'),'admin',sysdate(),'admin',sysdate(),'admin');
INSERT INTO USER_ROLE (USERID, ROLEID,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( (select userid from USER where username='admin'), (select ROLEID from ROLE where ROLENAME='user'),'admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 5 Pounds', 'https://bt.com', 'Get full data for 5 pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION,PRODUCTOFFERINGID, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 5 Pounds Price', 'Get full data for 5 pounds','28 days','Pounds','Pounds','5 Pounds','1',1,'https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION,PRODUCTOFFERINGID, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 5 Pounds Price', 'Get full data for 5 pounds','28 days','Pounds','Pounds','5 Pounds','1',1,'https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (1,'Full Data Plan 5 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (1,'Full Data Plan 5 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;