INSERT INTO USER (USERNAME, PASSWORD, ISACTIVE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('admin', 'admin', 'Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;
INSERT INTO USER_INFO (USERID, EMAILID, FIRSTNAME,MIDDLENAME,LASTNAME,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((select userid from USER where username='admin'), 'karthik727@gmail.com', 'karthik',null,'kumbhari','admin',sysdate(),'admin',sysdate(),'admin');
commit;
INSERT INTO USER_ADDRESS (USERID, ADDRESS, CITY,PINCODE,COUNTRY,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((select userid from USER where username='admin'), 'ECO WORLD BT', 'BENGALURU',560066,'INDIA','admin',sysdate(),'admin',sysdate(),'admin');
commit;
INSERT INTO ROLE (ROLENAME, ROLEDESCRIPTION,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( 'admin', 'Full access to the system','admin',sysdate(),'admin',sysdate(),'admin'); 
 INSERT INTO ROLE (ROLENAME, ROLEDESCRIPTION,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( 'user', 'User access to the system','admin',sysdate(),'admin',sysdate(),'admin'); 
 commit;
INSERT INTO USER_ROLE (USERID, ROLEID,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( (select userid from USER where username='admin'), (select ROLEID from ROLE where ROLENAME='admin'),'admin',sysdate(),'admin',sysdate(),'admin');
INSERT INTO USER_ROLE (USERID, ROLEID,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( (select userid from USER where username='admin'), (select ROLEID from ROLE where ROLENAME='user'),'admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 5 Pounds', 'https://bt.com', 'Get full data for 5 pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION,PRODUCTOFFERINGID, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 5 Pounds Price', 'Get full data for 5 pounds','28 days','Pounds','Pounds','5 Pounds','1',1,'https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION,PRODUCTOFFERINGID, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 5 Pounds Price', 'Get full data for 5 pounds','28 days','Pounds','Pounds','5 Pounds','1',1,'https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (1,'Full Data Plan 5 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (1,'Full Data Plan 5 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 
 
 INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 9 Pounds', 'https://bt.com', 'Get full data for 9 pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (5,'Full Data Plan 9 Pounds Price', 'Get full data for 9 pounds','28 days','Pounds','Pounds','9 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (5,'Full Data Plan 9 Pounds Price', 'Get full data for 9 pounds','28 days','Pounds','Pounds','9 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (5,'Full Data Plan 9 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES (5,'Full Data Plan 9 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 
 #Insert Scripts start here for product
 
  INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 13 Pounds', 'https://bt.com', 'Get full data for 13 Pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 13 Pounds'),'Full Data Plan 13 Pounds Price', 'Get full data for 13 Pounds','28 days','Pounds','Pounds','13 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 13 Pounds'),'Full Data Plan 13 Pounds Price', 'Get full data for 13 Pounds','28 days','Pounds','Pounds','13 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 13 Pounds'),'Full Data Plan 13 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 13 Pounds'),'Full Data Plan 13 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
  INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 15 Pounds', 'https://bt.com', 'Get full data for 15 Pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 15 Pounds'),'Full Data Plan 15 Pounds Price', 'Get full data for 15 Pounds','28 days','Pounds','Pounds','15 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 15 Pounds'),'Full Data Plan 15 Pounds Price', 'Get full data for 15 Pounds','28 days','Pounds','Pounds','15 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 15 Pounds'),'Full Data Plan 15 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 15 Pounds'),'Full Data Plan 15 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
  INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 17 Pounds', 'https://bt.com', 'Get full data for 17 Pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 17 Pounds'),'Full Data Plan 17 Pounds Price', 'Get full data for 17 Pounds','28 days','Pounds','Pounds','17 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 17 Pounds'),'Full Data Plan 17 Pounds Price', 'Get full data for 17 Pounds','28 days','Pounds','Pounds','17 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 17 Pounds'),'Full Data Plan 17 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 17 Pounds'),'Full Data Plan 17 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
  INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 19 Pounds', 'https://bt.com', 'Get full data for 19 Pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 19 Pounds'),'Full Data Plan 19 Pounds Price', 'Get full data for 19 Pounds','28 days','Pounds','Pounds','19 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 19 Pounds'),'Full Data Plan 19 Pounds Price', 'Get full data for 19 Pounds','28 days','Pounds','Pounds','19 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 19 Pounds'),'Full Data Plan 19 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 19 Pounds'),'Full Data Plan 19 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
  INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 21 Pounds', 'https://bt.com', 'Get full data for 21 Pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 21 Pounds'),'Full Data Plan 21 Pounds Price', 'Get full data for 21 Pounds','28 days','Pounds','Pounds','21 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 21 Pounds'),'Full Data Plan 21 Pounds Price', 'Get full data for 21 Pounds','28 days','Pounds','Pounds','21 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 21 Pounds'),'Full Data Plan 21 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 21 Pounds'),'Full Data Plan 21 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
  INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 23 Pounds', 'https://bt.com', 'Get full data for 23 Pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 23 Pounds'),'Full Data Plan 23 Pounds Price', 'Get full data for 23 Pounds','28 days','Pounds','Pounds','23 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 23 Pounds'),'Full Data Plan 23 Pounds Price', 'Get full data for 23 Pounds','28 days','Pounds','Pounds','23 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 23 Pounds'),'Full Data Plan 23 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 23 Pounds'),'Full Data Plan 23 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
  INSERT INTO PRODUCTOFFERING (NAME, HREF, DESCRIPTION,ISBUNDLE,LASTUPDATE,LIFECYCLESTATUS,VALIDFOR,VERSION,TYPE,BASETYPE,SCHEMALOCATION,ISSELLABLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('Full Data Plan 27 Pounds', 'https://bt.com', 'Get full data for 27 Pounds','N',sysdate(),'28 days','28 days','1','Data','Cell','UK','Y','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 27 Pounds'),'Full Data Plan 27 Pounds Price', 'Get full data for 27 Pounds','28 days','Pounds','Pounds','27 Pounds','1','https://bt.com','Data','Data','UK','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTOFFERINGPRICE (PRODUCTOFFERINGID,NAME,DESCRIPTION,VALIDFOR,PRICETYPE,UNITOFMEASURE,RECURRINGCHARGEPRICE,VERSION, HREF, TYPE,BASETYPE,SCHEMALOCATION,ISBUNDLE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 27 Pounds'),'Full Data Plan 27 Pounds Price', 'Get full data for 27 Pounds','28 days','Pounds','Pounds','27 Pounds','1','https://bt.com','Data','Data','INDIA','N','admin',sysdate(),'admin',sysdate(),'admin');
commit;

INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 27 Pounds'),'Full Data Plan 27 Pounds Price',1,'https://bt.com','DATA','admin',sysdate(),'admin',sysdate(),'admin');
 commit;
 
 INSERT INTO PRODUCTSPECIFICATIONREF (PRODUCTOFFERINGID,NAME,VERSION,HREF,REFERREDTYPE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((SELECT PRODUCTOFFERINGID FROM PRODUCTOFFERING WHERE NAME='Full Data Plan 27 Pounds'),'Full Data Plan 27 Pounds Price',1,'https://bt.com','PHONE','admin',sysdate(),'admin',sysdate(),'admin');
 commit;