
CREATE TABLE USER (   
    USERID int AUTO_INCREMENT,
    USERNAME varchar(30) NOT NULL,
    PASSWORD varchar(30) NOT NULL,   
    ISACTIVE varchar(1),
	CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERID)
);

CREATE TABLE USER_INFO (   
    USERINFOID int AUTO_INCREMENT,
    USERID int,
    EMAILID varchar(60),
    FIRSTNAME  varchar(60) NOT NULL,
    MIDDLENAME  varchar(60),
    LASTNAME varchar(60),
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERINFOID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);

CREATE TABLE USER_ADDRESS (   
    USERADDRESSID int AUTO_INCREMENT,
    USERID int,
    ADDRESS varchar(255),
    CITY varchar(255),
    PINCODE  int,
    COUNTRY varchar(255),
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERADDRESSID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);

CREATE TABLE ROLE (   
    ROLEID int AUTO_INCREMENT,
    ROLENAME varchar(255) NOT NULL,
    ROLEDESCRIPTION varchar(255),
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (ROLEID)
);

CREATE TABLE USER_ROLE (   
    USERROLEID int AUTO_INCREMENT,
    USERID int ,
    ROLEID int ,
    CREATEDBY varchar(30),
    CREATEDDATE DATE,
    LASTUPDATEDBY varchar(30),
    LASTUPDATEDDATE DATE,
    LASTUPDATEDLOGIN varchar(30),
    PRIMARY KEY (USERROLEID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID),
    FOREIGN KEY (ROLEID) REFERENCES ROLE(ROLEID)
);

commit;

#drop table USER_ROLE;
#drop table ROLE;
#drop table USER_ADDRESS;
#drop table USER_INFO;
#drop table USER;

commit;

alter table user ADD UNIQUE(username); 
commit;


