#select * from user;
INSERT INTO USER (USERNAME, PASSWORD, ISACTIVE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ('admin', 'admin', 'Y','admin',sysdate(),'admin',sysdate(),'admin');
#update user set username='user', password = 'user' where userid=2;
#delete from user where userid in (2,3,4);
commit;
INSERT INTO USER_INFO (USERID, EMAILID, FIRSTNAME,MIDDLENAME,LASTNAME,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((select userid from user where username='admin'), 'karthik727@gmail.com', 'karthik',null,'kumbhari','admin',sysdate(),'admin',sysdate(),'admin');
commit;
select * from USER_INFO;

desc USER_ADDRESS;

INSERT INTO USER_INFO (USERID, EMAILID, FIRSTNAME,MIDDLENAME,LASTNAME,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((select userid from user where username='admin'), 'karthik727@gmail.com', 'karthik',null,'kumbhari','admin',sysdate(),'admin',sysdate(),'admin');

INSERT INTO USER_ADDRESS (USERID, ADDRESS, CITY,PINCODE,COUNTRY,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ((select userid from user where username='admin'), 'ECO WORLD BT', 'BENGALURU',560066,'INDIA','admin',sysdate(),'admin',sysdate(),'admin');

select * from USER_ADDRESS;
DESC ROLE;
INSERT INTO ROLE (ROLENAME, ROLEDESCRIPTION,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( 'admin', 'Full access to the system','admin',sysdate(),'admin',sysdate(),'admin');
 
 INSERT INTO ROLE (ROLENAME, ROLEDESCRIPTION,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( 'user', 'User access to the system','admin',sysdate(),'admin',sysdate(),'admin');
 
 commit;
 
 select * from role;
 DESC USER_ROLE;
INSERT INTO USER_ROLE (USERID, ROLEID,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( (select userid from user where username='admin'), (select ROLEID from ROLE where ROLENAME='admin'),'admin',sysdate(),'admin',sysdate(),'admin');

INSERT INTO USER_ROLE (USERID, ROLEID,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN)
 VALUES ( (select userid from user where username='admin'), (select ROLEID from ROLE where ROLENAME='user'),'admin',sysdate(),'admin',sysdate(),'admin');

 commit;
 
 select * from user;
 select * from USER_INFO;
desc USER_INFO;
 select * from USER_ADDRESS;
 desc USER_ADDRESS;
 select * from ROLE;
 select * from USER_ROLE;
 
 SELECT USERID,USERNAME,PASSWORD,ISACTIVE FROM USER;
 
 SELECT USERID,USERNAME,PASSWORD,ISACTIVE,CREATEDBY,CREATEDDATE,LASTUPDATEDBY,LASTUPDATEDDATE,LASTUPDATEDLOGIN FROM USER LIMIT 10 OFFSET 0;
 
 
 SELECT

  USER.USERID,
  USER.USERNAME,
  USER.PASSWORD,
  USER.ISACTIVE,
  USER.CREATEDBY,
  USER.CREATEDDATE,
  USER.LASTUPDATEDBY,
  USER.LASTUPDATEDDATE,
  USER.LASTUPDATEDLOGIN,  
USER_INFO.USERINFOID,
USER_INFO.USERID,
USER_INFO.EMAILID,
USER_INFO.FIRSTNAME,
USER_INFO.MIDDLENAME,
USER_INFO.LASTNAME,
USER_INFO.CREATEDBY,
USER_INFO.CREATEDDATE,
USER_INFO.LASTUPDATEDBY,
USER_INFO.LASTUPDATEDDATE,
USER_INFO.LASTUPDATEDLOGIN,
USER_ADDRESS.USERADDRESSID,
USER_ADDRESS.USERID,
USER_ADDRESS.ADDRESS,
USER_ADDRESS.CITY,
USER_ADDRESS.PINCODE,
USER_ADDRESS.COUNTRY,
USER_ADDRESS.CREATEDBY,
USER_ADDRESS.CREATEDDATE,
USER_ADDRESS.LASTUPDATEDBY,
USER_ADDRESS.LASTUPDATEDDATE,
USER_ADDRESS.LASTUPDATEDLOGIN
FROM USER
JOIN USER_INFO 
  ON USER.USERID = USER_INFO.USERID
JOIN USER
  ON USER.USERID = USER_ADDRESS.USERID;
  
  
select PASSWORD from user WHERE USERID =1;

select * from USER_INFO;
select * from USER_ADDRESS;
#delete from user where userid = 14;
#delete from user_info where userinfoid IN(6,8);
#delete from USER_ADDRESS where USERADDRESSID IN(6,7);

select * from user_role;

desc user_role;
#update user set password = '$2a$10$l9ncaYlF5q4KzHfvtlzvq.FTq1sCP2./Tw1EpQ0JCa6mYQbZH0.M.' where userid =1;
commit;

select * from PRODUCTOFFERING;
delete from PRODUCTOFFERING where PRODUCTOFFERINGID IN (6);

desc PRODUCTOFFERING;

select * from PRODUCTOFFERINGPRICE;
delete from PRODUCTOFFERINGPRICE where PRODUCTOFFERINGPRICEID IN (3,4);
desc PRODUCTOFFERINGPRICE;
select * from PRODUCTSPECIFICATIONREF;
delete from PRODUCTSPECIFICATIONREF where PRODUCTSPECIFICATIONREFID IN (3,4);

desc PRODUCTSPECIFICATIONREF;
